# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/tjalogo.png

heroslogan: I build effective, user-friendly websites & web apps

intro: I'm Thom Allen, a freelance front-end developer based in London. I create responsive, efficient web experiences that satisfy clients & engage users. Currently I'm focusing on developing UI components for web apps with libraries like React and Vue.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/100x100"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Google Analytics Tracking ID
google_analytics:
